# Taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "teamookla/speedtest"

# Brews (packages)
brew "bat"
brew "exa"
brew "gcc"
brew "git"
brew "httpie"
brew "node"
brew "yarn"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "teamookla/speedtest/speedtest"

# Casks (Applications)
cask "1password"
cask "adguard"
cask "alfred"
cask "aerial"
cask "appcleaner"
cask "docker"
cask "firefox"
cask "fork"
cask "font-cascadia-code"
cask "font-cascadia-mono"
cask "font-fira-code"
cask "font-jetbrains-mono"
cask "iterm2"
cask "nordvpn"
cask "notion"
cask "postman"
cask "spotify"
cask "tutanota"
cask "typora"
cask "visual-studio-code"
cask "webpquicklook"
